import { transaction,pool } from '../../src/config/db.js';
await transaction(async db=>{
 if((await db.query("SELECT 1 FROM site_settings WHERE key='v2_seeded'")).rowCount) return;
 const ar = data=>({ar:data});
 const locations=[['Office desk','office-desk','مكتب العمل'],['Reception','reception','الاستقبال'],['Living room','living-room','غرفة المعيشة'],['Bedroom','bedroom','غرفة النوم'],['Balcony','balcony','الشرفة'],['Courtyard','courtyard','الفناء'],['Garden','garden','الحديقة'],['Containers','containers','الأحواض'],['Walls and fences','walls-fences','الجدران والأسوار'],['Shaded area','shade','مكان مظلل'],['Sunny area','sunny-area','مكان مشمس']];
 for(const [name,slug,arabic] of locations) await db.query('INSERT INTO suitable_locations(name,slug,translations) VALUES($1,$2,$3) ON CONFLICT(slug) DO NOTHING',[name,slug,ar({name:arabic})]);
 const office=(await db.query("INSERT INTO categories(name,slug,description,translations) VALUES('Office Plants','office-plants','Find greenery for your workspace.',$1) ON CONFLICT(slug) DO UPDATE SET slug=excluded.slug RETURNING id",[ar({name:'نباتات المكتب',description:'اختر نباتات تناسب مساحة عملك.'})])).rows[0];
 for(const [name,slug,arabic] of [['Desk Plants','desk-plants','نباتات سطح المكتب'],['Low-Light Plants','office-low-light','نباتات الإضاءة المنخفضة'],['Low-Maintenance Plants','office-low-maintenance','نباتات سهلة العناية'],['Reception Plants','reception-plants','نباتات الاستقبال'],['Large Office Plants','large-office-plants','نباتات المكاتب الكبيرة']]) await db.query('INSERT INTO categories(name,slug,parent_id,translations) VALUES($1,$2,$3,$4) ON CONFLICT(slug) DO NOTHING',[name,slug,office.id,ar({name:arabic})]);
 const faqs=[
 ['Ordering','How do I place an order?','Choose your plants, add them to your cart, and enter your delivery details at checkout.','كيف أطلب؟','اختر نباتاتك وأضفها إلى السلة ثم أدخل تفاصيل التوصيل عند إتمام الطلب.'],
 ['Payment','Which payment methods are available?','Cash on delivery is currently available. All prices are in Jordanian dinars.','ما طرق الدفع المتاحة؟','الدفع نقداً عند الاستلام متاح حالياً. جميع الأسعار بالدينار الأردني.'],
 ['Delivery','When will my plants arrive?','Check the estimated delivery dates for your city. Dates are guidance and depend on processing days and the delivery schedule.','متى تصل نباتاتي؟','تحقق من موعد التوصيل التقديري لمدينتك. يعتمد الموعد على أيام تجهيز الطلب وجدول التوصيل.'],
 ['Returns','How can I request a return?','Read the return policy, then open your account and select the delivered order item. The store reviews each request.','كيف أطلب إرجاع منتج؟','اقرأ سياسة الإرجاع ثم افتح حسابك واختر المنتج الذي تم توصيله. يراجع المتجر كل طلب.'],
 ['Plant care','Where can I find care information?','Each product page contains the available care details. Ask us if you need advice for your space.','أين أجد تعليمات العناية؟','تحتوي صفحة كل منتج على معلومات العناية المتاحة. تواصل معنا للحصول على مساعدة تناسب مساحتك.'],
 ['Accounts','Can I order without an account?','Yes. You can check out as a guest. An account helps you save your wishlist and view your orders.','هل أستطيع الطلب دون حساب؟','نعم، يمكنك الشراء كضيف. يساعدك الحساب على حفظ قائمة المفضلة ومتابعة طلباتك.'],
 ['Discounts','How do I use a discount code?','Enter a valid coupon in your cart or at checkout. Eligibility and limits are checked before your order is placed.','كيف أستخدم رمز الخصم؟','أدخل رمز الخصم في السلة أو عند إتمام الطلب. يتم التحقق من الشروط قبل تأكيد الطلب.'],
 ['Guarantee','Does every plant have a guarantee?','Guarantee coverage depends on the published policy and the product. Review the conditions before ordering.','هل يشمل الضمان كل النباتات؟','يعتمد الضمان على السياسة المنشورة والمنتج. راجع الشروط قبل الطلب.']];
 for(const [group,question,answer,aq,aa] of faqs) await db.query('INSERT INTO faqs(group_name,question,answer,translations) VALUES($1,$2,$3,$4)',[group,question,answer,ar({question:aq,answer:aa})]);
 await db.query("INSERT INTO delivery_rules(name,city,processing_days,minimum_days,maximum_days,cutoff_hour,translations) VALUES('Standard delivery','*',1,1,3,14,$1)",[ar({name:'التوصيل العادي'})]);
 for(const [name,city,lat,lon,arabic] of [['Amman highlands','Amman',31.9539,35.9106,'مرتفعات عمّان'],['Irbid northern highlands','Irbid',32.5568,35.8469,'مرتفعات إربد'],['Aqaba coastal climate','Aqaba',29.5321,35.0063,'مناخ العقبة الساحلي']]) await db.query('INSERT INTO climate_profiles(name,city,latitude,longitude,description,translations) VALUES($1,$2,$3,$4,$5,$6)',[name,city,lat,lon,'Seasonal guidance should be adjusted to local weather and the plant’s growing conditions.',ar({name:arabic,description:'إرشادات موسمية تتغير بحسب الطقس المحلي وظروف نمو النبات.'})]);
 // Draft policies require the owner to approve commercial terms before publication.
 await db.query("INSERT INTO return_policies(title,content,conditions,active,translations) VALUES('Returns and exchanges','Contact the store about a return within 14 days of completed delivery.','Items must be in their delivered condition. Requests are reviewed before approval.',false,$1)",[ar({title:'الإرجاع والاستبدال',content:'تواصل مع المتجر خلال 14 يوماً من اكتمال التوصيل.',conditions:'يجب أن تكون المنتجات بحالتها عند التسليم. تخضع الطلبات للمراجعة.'})]);
 await db.query("INSERT INTO guarantee_policies(title,conditions,exclusions,active,translations) VALUES('90-day plant guarantee','Follow the supplied care instructions and provide photos of the plant and the problem.','Damage caused by unsuitable care or accidental damage is excluded.',false,$1)",[ar({title:'ضمان النبات لمدة 90 يوماً',conditions:'اتبع تعليمات العناية وأرسل صوراً للنبات والمشكلة.',exclusions:'لا يشمل الأضرار الناتجة عن العناية غير المناسبة أو الحوادث.'})]);
 for(const [title,links,arabic] of [['Explore',[{label:'Shop plants',url:'/shop'},{label:'Office plants',url:'/shop?category=office-plants'},{label:'Compare plants',url:'/compare'}],'اكتشف'],['Customer care',[{label:'FAQs',url:'/faq'},{label:'Delivery',url:'/delivery'},{label:'Returns',url:'/returns'},{label:'Plant guarantee',url:'/guarantee'},{label:'Contact',url:'/contact'}],'خدمة العملاء'],['Your space',[{label:'My account',url:'/account'},{label:'Wishlist',url:'/wishlist'},{label:'Cart',url:'/cart'}],'مساحتك']]) await db.query('INSERT INTO footer_columns(title,links,translations) VALUES($1,$2,$3)',[title,JSON.stringify(links),ar({title:arabic})]);
 await db.query("INSERT INTO announcements(title,url,link_label,translations) VALUES('A little greenery. A brighter everyday.','/shop','Explore plants',$1)",[ar({title:'لمسة خضراء ليوم أجمل.',link_label:'اكتشف النباتات'})]);
 await db.query("INSERT INTO role_permissions SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name IN ('SUPER_ADMIN','ADMIN') ON CONFLICT DO NOTHING");
 await db.query("INSERT INTO role_permissions SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name='STORE_MANAGER' AND p.name IN ('faqs.manage','delivery.manage','returns.manage','guarantees.manage','calendar.manage','newsletter.manage','bundles.manage','announcements.manage','footer.manage','notifications.manage','translations.manage') ON CONFLICT DO NOTHING");
 await db.query("INSERT INTO role_permissions SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name='CONTENT_MANAGER' AND p.name IN ('faqs.manage','calendar.manage','announcements.manage','footer.manage','translations.manage') ON CONFLICT DO NOTHING");
 await db.query("INSERT INTO site_settings(key,value) VALUES('v2_seeded','true')");
});
await pool.end();
console.log('V2 content added. Google and email remain disabled; commercial policies are drafts.');
