import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
import {unlink} from 'node:fs/promises';
import {app} from '../src/app.js';
import {pool,query,transaction} from '../src/config/db.js';
import {deliveryDates} from '../src/services/v2.js';
import {changeOrderStatus} from '../src/services/checkout.js';
const client=request(app);let admin,customer,userId,product,variation,addon,bundle,order,photo;
const call=(method,url,body,token=admin)=>{let r=client[method]('/api'+url);if(token)r=r.set('Authorization','Bearer '+token);return body===undefined?r:r.send(body)};
const address={first_name:'V2',last_name:'Customer',phone:'0790000000',address:'Test street',city:'Amman',country:'Jordan'};
const email='v2-customer@example.com';
after(async()=>{if(photo)await unlink(new URL('../private-evidence/'+photo+'.webp',import.meta.url)).catch(()=>{});await pool.end()});
test('V2 content, Arabic display fields, delivery dates and restricted administration',async()=>{
 const login=await call('post','/auth/login',{email:process.env.SUPER_ADMIN_EMAIL,password:process.env.SUPER_ADMIN_PASSWORD},null);assert.equal(login.status,200);admin=login.body.token;
 const customerResult=await call('post','/auth/register',{name:'V2 Customer',email,password:'V2-Customer-Strong-123',confirm_password:'V2-Customer-Strong-123'},null);assert.equal(customerResult.status,201);customer=customerResult.body.token;userId=customerResult.body.user.id;
 const site=await call('get','/v2/site',undefined,null);assert.equal(site.status,200);assert.equal(site.body.google_enabled,false);assert.equal(site.body.email_enabled,false);assert.ok(site.body.footer.length);
 assert.equal((await call('get','/admin/v2/newsletter_subscribers',undefined,customer)).status,403);
 const faq=await client.get('/api/faqs').set('Accept-Language','ar');assert.ok(faq.body.some(f=>/[\u0600-\u06ff]/.test(f.question)));
 const rules={processing_days:1,minimum_days:1,maximum_days:3,weekend_days:[5,6],cutoff_hour:14,city:'Amman',name:'Test'};
 const dates=deliveryDates(rules,new Date('2026-09-17T12:00:00Z'));assert.equal(dates.earliest,'2026-09-22');assert.equal(dates.latest,'2026-09-24');
 assert.equal((await call('post','/admin/delivery_rules',{name:'Invalid',minimum_days:9,maximum_days:1})).status,400);
});
test('Variation stock, bundle validation, idempotency and atomic stock restoration',async()=>{
 let r=await call('post','/admin/products',{name:'V2 Plant',slug:'v2-test-plant',sku:'V2-P',regular_price:20,active:true});assert.equal(r.status,201,JSON.stringify(r.body));product=r.body;
 r=await call('post','/admin/product_variations',{product_id:product.id,name:'Large',sku:'V2-L',regular_price:25,stock_quantity:4,active:true,translations:{ar:{name:'كبير'}}});assert.equal(r.status,201,JSON.stringify(r.body));variation=r.body;
 addon=(await call('post','/admin/products',{name:'V2 Addon',slug:'v2-addon',sku:'V2-A',regular_price:10,active:true})).body;
 await call('post','/admin/inventory/'+addon.id,{quantity:10,reason:'Testing',stock_status:'in_stock',low_stock_threshold:1});
 bundle=(await call('post','/admin/bundles',{name:'V2 Set',base_product_id:product.id,discount_percent:10})).body;
 assert.equal((await call('post','/admin/bundle_items',{bundle_id:bundle.id,product_id:addon.id,quantity:1,optional:false})).status,201);
 assert.equal((await call('post','/cart/quote',{items:[{product_id:product.id,quantity:1}]})).status,400);
 assert.equal((await call('post','/cart/quote',{items:[{product_id:addon.id,variation_id:variation.id,quantity:1}]})).status,400);
 assert.equal((await call('post','/cart/quote',{items:[{product_id:product.id,variation_id:variation.id,bundle_id:bundle.id,quantity:1}]})).status,400);
 const items=[{product_id:product.id,variation_id:variation.id,bundle_id:bundle.id,quantity:1},{product_id:addon.id,bundle_id:bundle.id,quantity:1}];
 r=await call('post','/cart/quote',{items});assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.subtotal,35);assert.equal(r.body.bundle_discount,3.5);
 assert.equal((await call('post','/cart/quote',{items:[...items,{product_id:product.id,variation_id:variation.id,quantity:4}]})).status,400);
 await call('put','/cart',{items},customer);const cart=await call('get','/cart',undefined,customer);assert.equal(cart.body[0].variation_id,variation.id);
 const data={items,email,shipping_address:address,payment_method:'cod',idempotency_key:randomUUID()};r=await call('post','/checkout',data,customer);assert.equal(r.status,201,JSON.stringify(r.body));order=r.body;
 const replay=await call('post','/checkout',data,customer);assert.equal(replay.body.id,order.id);assert.equal((await query('SELECT stock_quantity FROM product_variations WHERE id=$1',[variation.id])).rows[0].stock_quantity,3);
 const detail=await call('get','/orders/'+order.id,undefined,customer);assert.equal(detail.body.items.find(i=>i.variation_id).variation_name,'Large');assert.ok(detail.body.delivery_estimate);
 assert.equal((await call('delete','/admin/product_variations/'+variation.id)).status,400);
 await call('put','/admin/orders/'+order.id,{status:'cancelled'});assert.equal((await query('SELECT stock_quantity FROM product_variations WHERE id=$1',[variation.id])).rows[0].stock_quantity,4);
});
test('Newsletter consent, deduplication, one-time welcome pricing and subscriptions without sending',async()=>{
 assert.equal((await call('post','/newsletter',{email,consent:false},null)).status,400);
 for(let i=0;i<2;i++)assert.equal((await call('post','/newsletter',{email,consent:true,language:'ar'},null)).status,200);
 assert.equal((await query('SELECT count(*)::int n FROM newsletter_subscribers WHERE email=$1',[email])).rows[0].n,1);
 const settings=(await call('get','/admin/settings')).body;
 await call('put','/admin/settings',{...settings,welcome_discount_enabled:true,welcome_discount_percent:10,welcome_discount_minimum:0,cod_enabled:true});
 const newEmail='v2-new@example.com';const registration=await call('post','/auth/register',{name:'New V2',email:newEmail,password:'V2-Customer-Strong-123',confirm_password:'V2-Customer-Strong-123'},null);const token=registration.body.token;
 await call('post','/newsletter',{email:newEmail,consent:true},null);
 const items=[{product_id:addon.id,quantity:1}];let q=await call('post','/cart/quote',{items},token);assert.equal(q.body.welcome_discount,1);
 const d={items,email:newEmail,shipping_address:address,payment_method:'cod',idempotency_key:randomUUID()};assert.equal((await call('post','/checkout',d,token)).status,201);
 q=await call('post','/cart/quote',{items},token);assert.equal(q.body.welcome_discount,0);
 for(let i=0;i<2;i++)assert.equal((await call('post','/stock-notifications',{email,product_id:product.id,variation_id:variation.id},null)).status,200);
 assert.equal((await query('SELECT count(*)::int n FROM stock_notifications WHERE email=$1',[email])).rows[0].n,1);
 assert.equal((await query("SELECT count(*)::int n FROM email_outbox WHERE status='sent'")).rows[0].n,0);
 await call('put','/admin/settings',settings);
});
test('Delivered-order eligibility, private evidence, ownership and claim review',async()=>{
 const policy=await call('post','/admin/guarantee_policies',{title:'V2 guarantee',duration_days:90,conditions:'Care correctly',evidence_required:true,product_ids:[addon.id],active:true});assert.equal(policy.status,201);
 const items=[{product_id:addon.id,quantity:1}];const result=await call('post','/checkout',{items,email,shipping_address:address,payment_method:'cod',idempotency_key:randomUUID()},customer);assert.equal(result.status,201);const id=result.body.id;
 const line=(await query('SELECT id FROM order_items WHERE order_id=$1',[id])).rows[0];
 assert.equal((await call('post','/service-requests/guarantees',{order_item_id:line.id,reason:'Plant problem'},customer)).status,400);
 for(const status of ['processing','shipped','completed'])assert.equal((await call('put','/admin/orders/'+id,{status})).status,200);
 assert.equal((await call('post','/service-requests/guarantees',{order_item_id:line.id,reason:'Plant problem'},customer)).status,400);
 const buffer=await sharp({create:{width:20,height:20,channels:3,background:'green'}}).png().toBuffer();const uploaded=await client.post('/api/claim-evidence').set('Authorization','Bearer '+customer).attach('image',buffer,'plant.png');assert.equal(uploaded.status,201);photo=uploaded.body.id;
 assert.equal((await client.get('/api/claim-evidence/'+photo)).status,401);
 const claim=await call('post','/service-requests/guarantees',{order_item_id:line.id,reason:'Leaves damaged',photos:[photo]},customer);assert.equal(claim.status,201,JSON.stringify(claim.body));
 assert.equal((await call('put','/admin/v2/guarantee_claims/'+claim.body.id,{status:'approved',response:'Replacement arranged'},customer)).status,403);
 assert.equal((await call('put','/admin/v2/guarantee_claims/'+claim.body.id,{status:'approved',response:'Replacement arranged'})).status,200);
 const requests=await call('get','/service-requests',undefined,customer);assert.equal(requests.body.guarantees[0].response,'Replacement arranged');
});
