import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useSaved} from '../context/Saved';
import {useLanguage} from '../context/Language';
import {api,money,effectivePrice} from '../api/client';
import {ProductGrid} from '../components/Products';
import {useData,Loading,ErrorState,SEO} from '../components/UI';
export function Wishlist(){const {wishlist}=useSaved();const {t}=useLanguage();const {data,error,loading}=useData(wishlist.length?'/products?limit=100&ids='+wishlist.join(','):null);return <div className="container v2-page"><SEO data={{title:t('Wishlist','المفضلة')}}/><h1>{t('Your little collection of favourites.','مجموعتك المفضلة.')}</h1>{!wishlist.length?<p>{t('Save a plant with the heart button to find it here.','اضغط على القلب لحفظ النبات هنا.')}</p>:loading?<Loading/>:error?<ErrorState message={error}/>:<ProductGrid products={data?.items}/>}</div>}
export function Compare(){const {compare,compareProduct}=useSaved();const {t}=useLanguage();const [plants,setPlants]=useState([]),[error,setError]=useState('');useEffect(()=>{let live=true;setError('');setPlants([]);if(compare.length)api('/products?ids='+compare.join(',')).then(r=>Promise.all(r.items.map(p=>api('/products/'+p.slug)))).then(p=>{if(live)setPlants(p)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[compare.join(',')]);const attrs=[...new Set(plants.flatMap(p=>p.attributes.map(a=>a.name)))];return <div className="container v2-page"><SEO data={{title:t('Compare plants','مقارنة النباتات')}}/><h1>{t('Find your perfect match.','اختر النبات الأنسب لك.')}</h1><p>{t('Compare up to three plants side by side.','قارن بين ثلاثة نباتات كحد أقصى.')}</p>{error&&<ErrorState message={error}/>} {!compare.length?<Link to="/shop">{t('Explore plants','اكتشف النباتات')} →</Link>:!plants.length&&!error?<Loading/>:<div className="compare-scroll"><table className="compare-table"><thead><tr><th>{t('Plant','النبات')}</th>{plants.map(p=><th key={p.id}><button className="text-button" onClick={()=>compareProduct(p.id)}>{t('Remove','إزالة')}</button><Link to={'/product/'+p.slug}><img src={p.main_image} alt={p.name}/><h2>{p.name}</h2></Link></th>)}</tr></thead><tbody>{[['Price',p=>money(effectivePrice(p))],['Availability',p=>p.stock_quantity>0?t('In stock','متوفر'):t('Out of stock','غير متوفر')],...attrs.map(name=>[name,p=>p.attributes.find(a=>a.name===name)?.value||'—'])].map(([name,get])=><tr key={name}><th>{name}</th>{plants.map(p=><td key={p.id}>{get(p)}</td>)}</tr>)}</tbody></table></div>}</div>}
