import {useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client';
import {useStore} from '../context/Store';
import {useLanguage} from '../context/Language';
import {useData,Loading,ErrorState,Modal,Field} from '../components/UI';
export function ServiceRequestButton({item}){
 const {t}=useLanguage();const {notify}=useStore();const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[type,setType]=useState('returns'),[photos,setPhotos]=useState([]);
 return <><button className="text-button" onClick={()=>setOpen(true)}>{t('Return / guarantee request','طلب إرجاع / ضمان')}</button>{open&&<Modal title={t('Get help with ','اطلب المساعدة بخصوص ')+item.name} onClose={()=>setOpen(false)}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const d=Object.fromEntries(new FormData(e.currentTarget));await api('/service-requests/'+type,{method:'POST',body:{order_item_id:item.id,reason:d.reason,notes:d.notes,quantity:Number(d.quantity||1),photos}});notify(t('Request submitted. Track updates in your account.','تم إرسال الطلب. تابع التحديثات في حسابك.'));setOpen(false);}catch(e){notify(e.message)}finally{setBusy(false)}}}><label className="field">{t('Request type','نوع الطلب')}<select value={type} onChange={e=>setType(e.target.value)}><option value="returns">{t('Return','إرجاع')}</option><option value="guarantees">{t('Plant guarantee','ضمان النبات')}</option></select></label><Field label={t('Reason / problem','السبب / المشكلة')} name="reason" required maxLength={500}/><Field as="textarea" label={t('Details','التفاصيل')} name="notes"/>{type==='returns'?<Field type="number" name="quantity" label={t('Quantity','الكمية')} defaultValue={1} min={1} max={item.quantity}/>:<label className="field">{t('Plant photos (up to 5)','صور النبات (حتى 5)')}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||photos.length>=5} onChange={async e=>{const file=e.target.files[0];if(!file)return;setBusy(true);try{const body=new FormData();body.append('image',file);const result=await api('/claim-evidence',{method:'POST',body});setPhotos(p=>[...p,result.id]);}catch(e){notify(e.message)}finally{setBusy(false)}}}/><small>{photos.length} {t('photos attached','صور مرفقة')}</small></label>}<p><Link to={type==='returns'?'/returns':'/guarantee'}>{t('Read the policy','اقرأ السياسة')}</Link></p><button className="button" disabled={busy}>{t('Submit request','إرسال الطلب')}</button></form></Modal>}</>;
}
export default function ServiceRequests(){const {data,error,loading}=useData('/service-requests');const {t}=useLanguage();if(loading)return <Loading/>;if(error)return <ErrorState message={error}/>;return <><h2>{t('Returns & guarantee requests','طلبات الإرجاع والضمان')}</h2>{[...data.returns.map(r=>({...r,type:'Return'})),...data.guarantees.map(r=>({...r,type:'Guarantee'}))].map(r=><article className="policy-card" key={r.type+r.id}><h3>{r.type} #{r.id}</h3><span className="badge">{r.status.replaceAll('_',' ')}</span><p>{r.reason||r.problem}</p>{r.response&&<p><strong>{t('Store response','رد المتجر')}: </strong>{r.response}</p>}{r.resolution&&<p>{r.resolution}</p>}</article>)}{!data.returns.length&&!data.guarantees.length&&<p>{t('No requests yet. Open a delivered order to submit a request.','لا توجد طلبات بعد. افتح طلباً تم توصيله لإرسال طلب المساعدة.')}</p>}</>}
