import {useState} from 'react';
import {useData,Loading,ErrorState,Modal,Field} from '../../components/UI';
import {api} from '../../api/client';
import {useStore} from '../../context/Store';
export default function V2Operations({type}) {
 const {data,error,loading,reload}=useData('/admin/v2/'+type);const {notify}=useStore();const [edit,setEdit]=useState(null),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const claims=['return_requests','guarantee_claims'].includes(type);const title={return_requests:'Return requests',guarantee_claims:'Guarantee claims',newsletter_subscribers:'Newsletter subscribers',stock_notifications:'Back-in-stock interest'}[type];
 if(loading)return <Loading/>;if(error)return <ErrorState message={error}/>;
 return <><div className="admin-title"><h1>{title}</h1>{type==='newsletter_subscribers'&&<button className="button" onClick={async()=>{try{const result=await api('/admin/v2/newsletter-export');const url=URL.createObjectURL(new Blob([result.csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=result.filename;a.click();URL.revokeObjectURL(url);}catch(e){notify(e.message)}}}>Export CSV</button>}</div>{!claims&&<p className="muted">Email sending is disabled. These records capture customer preferences only.</p>}<input aria-label="Search records" placeholder="Search records…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="table-wrap"><table><thead><tr><th>ID</th><th>{claims?'Order item':'Email'}</th><th>{claims?'Reason / problem':'Name / product'}</th><th>Status</th><th>Date</th>{(claims||type==='newsletter_subscribers')&&<th>Actions</th>}</tr></thead><tbody>{data.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())).map(r=><tr key={r.id}><td>{r.id}</td><td>{claims?r.order_item_id:r.email}</td><td>{r.reason||r.problem||r.name||r.product_id}</td><td>{r.status}</td><td>{new Date(r.created_at).toLocaleDateString()}</td>{type==='newsletter_subscribers'&&<td><button className="text-button" disabled={r.status==='unsubscribed'} onClick={async()=>{try{await api('/admin/v2/newsletter_subscribers/'+r.id,{method:'PUT',body:{status:'unsubscribed'}});reload()}catch(e){notify(e.message)}}}>Unsubscribe</button></td>}{claims&&<td><button className="text-button" onClick={()=>setEdit(r)}>Review</button></td>}</tr>)}</tbody></table></div>{!data.length&&<p>No records yet.</p>}{edit&&<Modal title={title+' #'+edit.id} onClose={()=>setEdit(null)}><p>{edit.reason||edit.problem}</p><p>{edit.notes}</p>{edit.photos?.map(photo=><Evidence key={photo} id={photo}/>)}<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/admin/v2/'+type+'/'+edit.id,{method:'PUT',body:Object.fromEntries(new FormData(e.currentTarget))});setEdit(null);reload();notify('Request updated.');}catch(e){notify(e.message)}finally{setBusy(false)}}}><label className="field">Status<select name="status" defaultValue={edit.status}>{['pending','information_requested','approved','rejected',...(type==='return_requests'?['received']:[]),'resolved'].map(s=><option key={s}>{s}</option>)}</select></label><Field as="textarea" label="Customer response" name="response" defaultValue={edit.response}/>{type==='guarantee_claims'&&<Field label="Resolution" name="resolution" defaultValue={edit.resolution}/>}<button className="button" disabled={busy}>Save review</button></form></Modal>}</>;
}
import {useEffect} from 'react';
function Evidence({id}){const [url,setUrl]=useState('');useEffect(()=>{let active=true;let object;fetch('/api/claim-evidence/'+id,{headers:{Authorization:'Bearer '+sessionStorage.getItem('gharsa_token')}}).then(r=>{if(!r.ok)throw Error();return r.blob()}).then(b=>{object=URL.createObjectURL(b);if(active)setUrl(object)}).catch(()=>{});return()=>{active=false;if(object)URL.revokeObjectURL(object)}},[id]);return url?<img className="claim-photo" src={url} alt="Claim evidence"/>:null;}
